---
# subnet can only be [ 'db', 'app' ] for dev

dev_instance_detail:

  - name: app
    instances: 0
    subnet: app
    instance_type: m4.large
    ami_image: "{{centos7_ami}}"
    userdata_template: default.j2
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 40

  - name: clouderamgr
    instances: 0
    subnet: app
    instance_type: m4.large
    ami_image: "{{centos7_ami}}"
    userdata_template: default.j2
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 100

  - name: clouderagent
    instances: 0
    subnet: app
    instance_type: m4.large
    ami_image: "{{centos7_ami}}"
    userdata_template: default.j2
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 100

  - name: clouderadbagent
    instances: 0
    subnet: app
    instance_type: m4.xlarge
    ami_image: "{{centos7_ami}}"
    userdata_template: default.j2
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 100

  - name: hadoopnn
    instances: 0
    subnet: app
    instance_type: m4.xlarge
    ami_image: "{{centos7_ami}}"
    userdata_template: default.j2
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 100

  - name: hadoopnrmgr
    instances: 0
    subnet: app
    instance_type: m4.xlarge
    ami_image: "{{centos7_ami}}"
    userdata_template: default.j2
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 100

  - name: hadoopslave
    instances: 0
    subnet: app
    instance_type: m4.large
    ami_image: "{{centos7_ami}}"
    userdata_template: default.j2
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 100
